# Convenience targets. The single source of truth for the wire is
# `proto/actor.proto`; everything under `src/actor/_proto/` is
# generated by `make proto` and committed so the wheel build doesn't
# need protoc on consumers' machines.
#
# CI verifies regenerate-idempotency with `make check-proto`.

.PHONY: proto check-proto test e2e

proto:
	uv run protoc -I proto --python_betterproto_out=src/actor/_proto proto/actor.proto

check-proto:
	@tmpdir=$$(mktemp -d); \
	uv run protoc -I proto --python_betterproto_out=$$tmpdir proto/actor.proto && \
	diff -ruN src/actor/_proto $$tmpdir; rc=$$?; \
	rm -rf $$tmpdir; \
	if [ $$rc -ne 0 ]; then \
		echo "ERROR: generated code is stale; run 'make proto' and commit"; \
		exit 1; \
	fi

test:
	uv run python -m unittest discover tests

e2e:
	uv run python -m unittest discover e2e/tests
