# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: actor.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    AsyncIterable,
    AsyncIterator,
    Dict,
    Iterable,
    List,
    Optional,
    Union,
)

import betterproto
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase

if TYPE_CHECKING:
    import grpclib.server
    from betterproto.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline


class AgentKind(betterproto.Enum):
    UNSPECIFIED = 0
    CLAUDE = 1
    CODEX = 2


class Status(betterproto.Enum):
    UNSPECIFIED = 0
    IDLE = 1
    RUNNING = 2
    DONE = 3
    ERROR = 4
    STOPPED = 5
    INTERACTIVE = 6


class LogEntryKind(betterproto.Enum):
    UNSPECIFIED = 0
    USER = 1
    ASSISTANT = 2
    THINKING = 3
    TOOL_USE = 4
    TOOL_RESULT = 5


@dataclass(eq=False, repr=False)
class ActorConfig(betterproto.Message):
    actor_keys: Dict[str, str] = betterproto.map_field(
        1, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )
    agent_args: Dict[str, str] = betterproto.map_field(
        2, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )


@dataclass(eq=False, repr=False)
class Actor(betterproto.Message):
    name: str = betterproto.string_field(1)
    agent: "AgentKind" = betterproto.enum_field(2)
    agent_session: Optional[str] = betterproto.string_field(3, optional=True)
    dir: str = betterproto.string_field(4)
    source_repo: Optional[str] = betterproto.string_field(5, optional=True)
    base_branch: Optional[str] = betterproto.string_field(6, optional=True)
    worktree: bool = betterproto.bool_field(7)
    parent: Optional[str] = betterproto.string_field(8, optional=True)
    config: "ActorConfig" = betterproto.message_field(9)
    created_at: str = betterproto.string_field(10)
    updated_at: str = betterproto.string_field(11)


@dataclass(eq=False, repr=False)
class Run(betterproto.Message):
    id: int = betterproto.int64_field(1)
    actor_name: str = betterproto.string_field(2)
    prompt: str = betterproto.string_field(3)
    status: "Status" = betterproto.enum_field(4)
    exit_code: Optional[int] = betterproto.int32_field(5, optional=True)
    pid: Optional[int] = betterproto.int32_field(6, optional=True)
    config: "ActorConfig" = betterproto.message_field(7)
    started_at: str = betterproto.string_field(8)
    finished_at: Optional[str] = betterproto.string_field(9, optional=True)


@dataclass(eq=False, repr=False)
class Role(betterproto.Message):
    name: str = betterproto.string_field(1)
    agent: Optional[str] = betterproto.string_field(2, optional=True)
    prompt: Optional[str] = betterproto.string_field(3, optional=True)
    description: Optional[str] = betterproto.string_field(4, optional=True)
    config: Dict[str, str] = betterproto.map_field(
        5, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )


@dataclass(eq=False, repr=False)
class LogEntry(betterproto.Message):
    kind: "LogEntryKind" = betterproto.enum_field(1)
    timestamp: Optional[str] = betterproto.string_field(2, optional=True)
    text: str = betterproto.string_field(3)
    name: str = betterproto.string_field(4)
    input: str = betterproto.string_field(5)
    content: str = betterproto.string_field(6)
    usage: Dict[str, int] = betterproto.map_field(
        7, betterproto.TYPE_STRING, betterproto.TYPE_INT32
    )
    """Empty map → no usage attached for this entry."""

    has_usage: bool = betterproto.bool_field(8)


@dataclass(eq=False, repr=False)
class DiscardResult(betterproto.Message):
    names: List[str] = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class RunStartResult(betterproto.Message):
    run_id: int = betterproto.int64_field(1)
    pid: Optional[int] = betterproto.int32_field(2, optional=True)
    status: "Status" = betterproto.enum_field(3)


@dataclass(eq=False, repr=False)
class RunResult(betterproto.Message):
    run_id: int = betterproto.int64_field(1)
    actor: str = betterproto.string_field(2)
    status: "Status" = betterproto.enum_field(3)
    exit_code: Optional[int] = betterproto.int32_field(4, optional=True)
    output: str = betterproto.string_field(5)


@dataclass(eq=False, repr=False)
class StopResult(betterproto.Message):
    name: str = betterproto.string_field(1)
    was_alive: bool = betterproto.bool_field(2)


@dataclass(eq=False, repr=False)
class ActorDetail(betterproto.Message):
    actor: "Actor" = betterproto.message_field(1)
    status: "Status" = betterproto.enum_field(2)
    runs: List["Run"] = betterproto.message_field(3)
    total_runs: int = betterproto.int32_field(4)
    runs_limit: int = betterproto.int32_field(5)


@dataclass(eq=False, repr=False)
class LogsResult(betterproto.Message):
    session_id: Optional[str] = betterproto.string_field(1, optional=True)
    entries: List["LogEntry"] = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class Notification(betterproto.Message):
    actor: str = betterproto.string_field(1)
    event: str = betterproto.string_field(2)
    """run_completed" | "actor_discarded"""

    run_id: Optional[int] = betterproto.int64_field(3, optional=True)
    status: Optional["Status"] = betterproto.enum_field(4, optional=True)
    output: Optional[str] = betterproto.string_field(5, optional=True)
    timestamp: float = betterproto.double_field(6)


@dataclass(eq=False, repr=False)
class NewActorRequest(betterproto.Message):
    name: str = betterproto.string_field(1)
    dir: Optional[str] = betterproto.string_field(2, optional=True)
    no_worktree: bool = betterproto.bool_field(3)
    base: Optional[str] = betterproto.string_field(4, optional=True)
    agent_name: Optional[str] = betterproto.string_field(5, optional=True)
    config: "ActorConfig" = betterproto.message_field(6)
    role_name: Optional[str] = betterproto.string_field(7, optional=True)


@dataclass(eq=False, repr=False)
class NewActorResponse(betterproto.Message):
    actor: "Actor" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class DiscardActorRequest(betterproto.Message):
    name: str = betterproto.string_field(1)
    force: bool = betterproto.bool_field(2)


@dataclass(eq=False, repr=False)
class DiscardActorResponse(betterproto.Message):
    result: "DiscardResult" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class ConfigActorRequest(betterproto.Message):
    name: str = betterproto.string_field(1)
    pairs: List[str] = betterproto.string_field(2)
    """Empty `pairs` = view; non-empty = set."""


@dataclass(eq=False, repr=False)
class ConfigActorResponse(betterproto.Message):
    config: "ActorConfig" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class StartRunRequest(betterproto.Message):
    name: str = betterproto.string_field(1)
    prompt: str = betterproto.string_field(2)
    config: "ActorConfig" = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class StartRunResponse(betterproto.Message):
    result: "RunStartResult" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class WaitForRunRequest(betterproto.Message):
    run_id: int = betterproto.int64_field(1)


@dataclass(eq=False, repr=False)
class WaitForRunResponse(betterproto.Message):
    result: "RunResult" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class RunActorRequest(betterproto.Message):
    name: str = betterproto.string_field(1)
    prompt: str = betterproto.string_field(2)
    config: "ActorConfig" = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class RunActorResponse(betterproto.Message):
    result: "RunResult" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class StopActorRequest(betterproto.Message):
    name: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class StopActorResponse(betterproto.Message):
    result: "StopResult" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class GetActorRequest(betterproto.Message):
    name: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class GetActorResponse(betterproto.Message):
    actor: "Actor" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class ActorExistsRequest(betterproto.Message):
    name: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class ActorExistsResponse(betterproto.Message):
    exists: bool = betterproto.bool_field(1)


@dataclass(eq=False, repr=False)
class ListActorsRequest(betterproto.Message):
    status_filter: Optional[str] = betterproto.string_field(1, optional=True)


@dataclass(eq=False, repr=False)
class ListActorsResponse(betterproto.Message):
    actors: List["Actor"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class ActorStatusRequest(betterproto.Message):
    name: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class ActorStatusResponse(betterproto.Message):
    status: "Status" = betterproto.enum_field(1)


@dataclass(eq=False, repr=False)
class LatestRunRequest(betterproto.Message):
    actor_name: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class LatestRunResponse(betterproto.Message):
    run: Optional["Run"] = betterproto.message_field(1, optional=True)
    """Unset when there's no run yet."""


@dataclass(eq=False, repr=False)
class ShowActorRequest(betterproto.Message):
    name: str = betterproto.string_field(1)
    runs_limit: int = betterproto.int32_field(2)


@dataclass(eq=False, repr=False)
class ShowActorResponse(betterproto.Message):
    detail: "ActorDetail" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class ListRunsRequest(betterproto.Message):
    actor_name: str = betterproto.string_field(1)
    limit: int = betterproto.int32_field(2)


@dataclass(eq=False, repr=False)
class ListRunsResponse(betterproto.Message):
    runs: List["Run"] = betterproto.message_field(1)
    total: int = betterproto.int32_field(2)


@dataclass(eq=False, repr=False)
class GetRunRequest(betterproto.Message):
    run_id: int = betterproto.int64_field(1)


@dataclass(eq=False, repr=False)
class GetRunResponse(betterproto.Message):
    run: Optional["Run"] = betterproto.message_field(1, optional=True)


@dataclass(eq=False, repr=False)
class GetLogsRequest(betterproto.Message):
    actor_name: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class GetLogsResponse(betterproto.Message):
    result: "LogsResult" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class ListRolesRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class ListRolesResponse(betterproto.Message):
    roles: Dict[str, "Role"] = betterproto.map_field(
        1, betterproto.TYPE_STRING, betterproto.TYPE_MESSAGE
    )
    """Map keyed by role name; values are full role records."""


@dataclass(eq=False, repr=False)
class PublishNotificationRequest(betterproto.Message):
    notification: "Notification" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class PublishNotificationResponse(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class GetServerInfoRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class GetServerInfoResponse(betterproto.Message):
    pid: int = betterproto.int32_field(1)
    started_at: str = betterproto.string_field(2)
    """Daemon start time (ISO 8601 UTC)."""

    version: str = betterproto.string_field(3)
    """actor-sh version the daemon was built / installed with."""

    connection_count: int = betterproto.int32_field(4)
    """Number of currently-active client streams (rough load gauge)."""

    fingerprint: str = betterproto.string_field(5)
    """
    Per-daemon identity fingerprint, "sha256:<hex>". Phase 4: used as
     the published TXT record + shown by `actor servers`. Phase 6: same
     string drives mTLS pinning.
    """

    instance_name: str = betterproto.string_field(6)
    """
    Service-instance name advertised over zeroconf (defaults to
     hostname). Empty when zeroconf publishing failed.
    """


@dataclass(eq=False, repr=False)
class ServerRecord(betterproto.Message):
    """
    One discovered (or local) actord on the network. The local daemon
     is included with `is_self=true` so `actor servers` can confirm
     "yes, I am advertising" with no special-casing.
    """

    instance_name: str = betterproto.string_field(1)
    host: str = betterproto.string_field(2)
    port: int = betterproto.int32_field(3)
    fingerprint: str = betterproto.string_field(4)
    version: str = betterproto.string_field(5)
    user: str = betterproto.string_field(6)
    pid: int = betterproto.int32_field(7)
    is_self: bool = betterproto.bool_field(8)
    last_seen: float = betterproto.double_field(9)
    """
    Unix epoch seconds. Set when the record was first seen / last
     refreshed by zeroconf. 0 for the local self record.
    """


@dataclass(eq=False, repr=False)
class ListServersRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class ListServersResponse(betterproto.Message):
    servers: List["ServerRecord"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class SubscribeNotificationsRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class OpenSession(betterproto.Message):
    actor_name: str = betterproto.string_field(1)
    cols: Optional[int] = betterproto.uint32_field(2, optional=True)
    rows: Optional[int] = betterproto.uint32_field(3, optional=True)


@dataclass(eq=False, repr=False)
class ResizeRequest(betterproto.Message):
    cols: int = betterproto.uint32_field(1)
    rows: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class SignalRequest(betterproto.Message):
    signal_number: int = betterproto.int32_field(1)
    """POSIX signal number to forward (e.g. 2 for SIGINT)."""


@dataclass(eq=False, repr=False)
class ClientFrame(betterproto.Message):
    open: "OpenSession" = betterproto.message_field(1, group="kind")
    stdin: bytes = betterproto.bytes_field(2, group="kind")
    resize: "ResizeRequest" = betterproto.message_field(3, group="kind")
    signal: "SignalRequest" = betterproto.message_field(4, group="kind")


@dataclass(eq=False, repr=False)
class ExitInfo(betterproto.Message):
    exit_code: int = betterproto.int32_field(1)
    final_status: "Status" = betterproto.enum_field(2)


@dataclass(eq=False, repr=False)
class ServerFrame(betterproto.Message):
    stdout: bytes = betterproto.bytes_field(1, group="kind")
    stderr: bytes = betterproto.bytes_field(2, group="kind")
    exit: "ExitInfo" = betterproto.message_field(3, group="kind")


class ActorServiceStub(betterproto.ServiceStub):
    async def new_actor(
        self,
        new_actor_request: "NewActorRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "NewActorResponse":
        return await self._unary_unary(
            "/actor.v1.ActorService/NewActor",
            new_actor_request,
            NewActorResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def discard_actor(
        self,
        discard_actor_request: "DiscardActorRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "DiscardActorResponse":
        return await self._unary_unary(
            "/actor.v1.ActorService/DiscardActor",
            discard_actor_request,
            DiscardActorResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def config_actor(
        self,
        config_actor_request: "ConfigActorRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "ConfigActorResponse":
        return await self._unary_unary(
            "/actor.v1.ActorService/ConfigActor",
            config_actor_request,
            ConfigActorResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def start_run(
        self,
        start_run_request: "StartRunRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "StartRunResponse":
        return await self._unary_unary(
            "/actor.v1.ActorService/StartRun",
            start_run_request,
            StartRunResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def wait_for_run(
        self,
        wait_for_run_request: "WaitForRunRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "WaitForRunResponse":
        return await self._unary_unary(
            "/actor.v1.ActorService/WaitForRun",
            wait_for_run_request,
            WaitForRunResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def run_actor(
        self,
        run_actor_request: "RunActorRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "RunActorResponse":
        return await self._unary_unary(
            "/actor.v1.ActorService/RunActor",
            run_actor_request,
            RunActorResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def stop_actor(
        self,
        stop_actor_request: "StopActorRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "StopActorResponse":
        return await self._unary_unary(
            "/actor.v1.ActorService/StopActor",
            stop_actor_request,
            StopActorResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_actor(
        self,
        get_actor_request: "GetActorRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "GetActorResponse":
        return await self._unary_unary(
            "/actor.v1.ActorService/GetActor",
            get_actor_request,
            GetActorResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def actor_exists(
        self,
        actor_exists_request: "ActorExistsRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "ActorExistsResponse":
        return await self._unary_unary(
            "/actor.v1.ActorService/ActorExists",
            actor_exists_request,
            ActorExistsResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def list_actors(
        self,
        list_actors_request: "ListActorsRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "ListActorsResponse":
        return await self._unary_unary(
            "/actor.v1.ActorService/ListActors",
            list_actors_request,
            ListActorsResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def actor_status(
        self,
        actor_status_request: "ActorStatusRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "ActorStatusResponse":
        return await self._unary_unary(
            "/actor.v1.ActorService/ActorStatus",
            actor_status_request,
            ActorStatusResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def latest_run(
        self,
        latest_run_request: "LatestRunRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "LatestRunResponse":
        return await self._unary_unary(
            "/actor.v1.ActorService/LatestRun",
            latest_run_request,
            LatestRunResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def show_actor(
        self,
        show_actor_request: "ShowActorRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "ShowActorResponse":
        return await self._unary_unary(
            "/actor.v1.ActorService/ShowActor",
            show_actor_request,
            ShowActorResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def list_runs(
        self,
        list_runs_request: "ListRunsRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "ListRunsResponse":
        return await self._unary_unary(
            "/actor.v1.ActorService/ListRuns",
            list_runs_request,
            ListRunsResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_run(
        self,
        get_run_request: "GetRunRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "GetRunResponse":
        return await self._unary_unary(
            "/actor.v1.ActorService/GetRun",
            get_run_request,
            GetRunResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_logs(
        self,
        get_logs_request: "GetLogsRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "GetLogsResponse":
        return await self._unary_unary(
            "/actor.v1.ActorService/GetLogs",
            get_logs_request,
            GetLogsResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def list_roles(
        self,
        list_roles_request: "ListRolesRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "ListRolesResponse":
        return await self._unary_unary(
            "/actor.v1.ActorService/ListRoles",
            list_roles_request,
            ListRolesResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def publish_notification(
        self,
        publish_notification_request: "PublishNotificationRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "PublishNotificationResponse":
        return await self._unary_unary(
            "/actor.v1.ActorService/PublishNotification",
            publish_notification_request,
            PublishNotificationResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def subscribe_notifications(
        self,
        subscribe_notifications_request: "SubscribeNotificationsRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> AsyncIterator[Notification]:
        async for response in self._unary_stream(
            "/actor.v1.ActorService/SubscribeNotifications",
            subscribe_notifications_request,
            Notification,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        ):
            yield response

    async def get_server_info(
        self,
        get_server_info_request: "GetServerInfoRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "GetServerInfoResponse":
        return await self._unary_unary(
            "/actor.v1.ActorService/GetServerInfo",
            get_server_info_request,
            GetServerInfoResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def list_servers(
        self,
        list_servers_request: "ListServersRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "ListServersResponse":
        return await self._unary_unary(
            "/actor.v1.ActorService/ListServers",
            list_servers_request,
            ListServersResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def interactive_session(
        self,
        client_frame_iterator: Union[AsyncIterable[ClientFrame], Iterable[ClientFrame]],
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> AsyncIterator[ServerFrame]:
        async for response in self._stream_stream(
            "/actor.v1.ActorService/InteractiveSession",
            client_frame_iterator,
            ClientFrame,
            ServerFrame,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        ):
            yield response


class ActorServiceBase(ServiceBase):

    async def new_actor(
        self, new_actor_request: "NewActorRequest"
    ) -> "NewActorResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def discard_actor(
        self, discard_actor_request: "DiscardActorRequest"
    ) -> "DiscardActorResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def config_actor(
        self, config_actor_request: "ConfigActorRequest"
    ) -> "ConfigActorResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def start_run(
        self, start_run_request: "StartRunRequest"
    ) -> "StartRunResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def wait_for_run(
        self, wait_for_run_request: "WaitForRunRequest"
    ) -> "WaitForRunResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def run_actor(
        self, run_actor_request: "RunActorRequest"
    ) -> "RunActorResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def stop_actor(
        self, stop_actor_request: "StopActorRequest"
    ) -> "StopActorResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_actor(
        self, get_actor_request: "GetActorRequest"
    ) -> "GetActorResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def actor_exists(
        self, actor_exists_request: "ActorExistsRequest"
    ) -> "ActorExistsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def list_actors(
        self, list_actors_request: "ListActorsRequest"
    ) -> "ListActorsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def actor_status(
        self, actor_status_request: "ActorStatusRequest"
    ) -> "ActorStatusResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def latest_run(
        self, latest_run_request: "LatestRunRequest"
    ) -> "LatestRunResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def show_actor(
        self, show_actor_request: "ShowActorRequest"
    ) -> "ShowActorResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def list_runs(
        self, list_runs_request: "ListRunsRequest"
    ) -> "ListRunsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_run(self, get_run_request: "GetRunRequest") -> "GetRunResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_logs(self, get_logs_request: "GetLogsRequest") -> "GetLogsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def list_roles(
        self, list_roles_request: "ListRolesRequest"
    ) -> "ListRolesResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def publish_notification(
        self, publish_notification_request: "PublishNotificationRequest"
    ) -> "PublishNotificationResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def subscribe_notifications(
        self, subscribe_notifications_request: "SubscribeNotificationsRequest"
    ) -> AsyncIterator[Notification]:
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)
        yield Notification()

    async def get_server_info(
        self, get_server_info_request: "GetServerInfoRequest"
    ) -> "GetServerInfoResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def list_servers(
        self, list_servers_request: "ListServersRequest"
    ) -> "ListServersResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def interactive_session(
        self, client_frame_iterator: AsyncIterator[ClientFrame]
    ) -> AsyncIterator[ServerFrame]:
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)
        yield ServerFrame()

    async def __rpc_new_actor(
        self, stream: "grpclib.server.Stream[NewActorRequest, NewActorResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.new_actor(request)
        await stream.send_message(response)

    async def __rpc_discard_actor(
        self, stream: "grpclib.server.Stream[DiscardActorRequest, DiscardActorResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.discard_actor(request)
        await stream.send_message(response)

    async def __rpc_config_actor(
        self, stream: "grpclib.server.Stream[ConfigActorRequest, ConfigActorResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.config_actor(request)
        await stream.send_message(response)

    async def __rpc_start_run(
        self, stream: "grpclib.server.Stream[StartRunRequest, StartRunResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.start_run(request)
        await stream.send_message(response)

    async def __rpc_wait_for_run(
        self, stream: "grpclib.server.Stream[WaitForRunRequest, WaitForRunResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.wait_for_run(request)
        await stream.send_message(response)

    async def __rpc_run_actor(
        self, stream: "grpclib.server.Stream[RunActorRequest, RunActorResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.run_actor(request)
        await stream.send_message(response)

    async def __rpc_stop_actor(
        self, stream: "grpclib.server.Stream[StopActorRequest, StopActorResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.stop_actor(request)
        await stream.send_message(response)

    async def __rpc_get_actor(
        self, stream: "grpclib.server.Stream[GetActorRequest, GetActorResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_actor(request)
        await stream.send_message(response)

    async def __rpc_actor_exists(
        self, stream: "grpclib.server.Stream[ActorExistsRequest, ActorExistsResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.actor_exists(request)
        await stream.send_message(response)

    async def __rpc_list_actors(
        self, stream: "grpclib.server.Stream[ListActorsRequest, ListActorsResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.list_actors(request)
        await stream.send_message(response)

    async def __rpc_actor_status(
        self, stream: "grpclib.server.Stream[ActorStatusRequest, ActorStatusResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.actor_status(request)
        await stream.send_message(response)

    async def __rpc_latest_run(
        self, stream: "grpclib.server.Stream[LatestRunRequest, LatestRunResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.latest_run(request)
        await stream.send_message(response)

    async def __rpc_show_actor(
        self, stream: "grpclib.server.Stream[ShowActorRequest, ShowActorResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.show_actor(request)
        await stream.send_message(response)

    async def __rpc_list_runs(
        self, stream: "grpclib.server.Stream[ListRunsRequest, ListRunsResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.list_runs(request)
        await stream.send_message(response)

    async def __rpc_get_run(
        self, stream: "grpclib.server.Stream[GetRunRequest, GetRunResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_run(request)
        await stream.send_message(response)

    async def __rpc_get_logs(
        self, stream: "grpclib.server.Stream[GetLogsRequest, GetLogsResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_logs(request)
        await stream.send_message(response)

    async def __rpc_list_roles(
        self, stream: "grpclib.server.Stream[ListRolesRequest, ListRolesResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.list_roles(request)
        await stream.send_message(response)

    async def __rpc_publish_notification(
        self,
        stream: "grpclib.server.Stream[PublishNotificationRequest, PublishNotificationResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.publish_notification(request)
        await stream.send_message(response)

    async def __rpc_subscribe_notifications(
        self,
        stream: "grpclib.server.Stream[SubscribeNotificationsRequest, Notification]",
    ) -> None:
        request = await stream.recv_message()
        await self._call_rpc_handler_server_stream(
            self.subscribe_notifications,
            stream,
            request,
        )

    async def __rpc_get_server_info(
        self,
        stream: "grpclib.server.Stream[GetServerInfoRequest, GetServerInfoResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_server_info(request)
        await stream.send_message(response)

    async def __rpc_list_servers(
        self, stream: "grpclib.server.Stream[ListServersRequest, ListServersResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.list_servers(request)
        await stream.send_message(response)

    async def __rpc_interactive_session(
        self, stream: "grpclib.server.Stream[ClientFrame, ServerFrame]"
    ) -> None:
        request = stream.__aiter__()
        await self._call_rpc_handler_server_stream(
            self.interactive_session,
            stream,
            request,
        )

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/actor.v1.ActorService/NewActor": grpclib.const.Handler(
                self.__rpc_new_actor,
                grpclib.const.Cardinality.UNARY_UNARY,
                NewActorRequest,
                NewActorResponse,
            ),
            "/actor.v1.ActorService/DiscardActor": grpclib.const.Handler(
                self.__rpc_discard_actor,
                grpclib.const.Cardinality.UNARY_UNARY,
                DiscardActorRequest,
                DiscardActorResponse,
            ),
            "/actor.v1.ActorService/ConfigActor": grpclib.const.Handler(
                self.__rpc_config_actor,
                grpclib.const.Cardinality.UNARY_UNARY,
                ConfigActorRequest,
                ConfigActorResponse,
            ),
            "/actor.v1.ActorService/StartRun": grpclib.const.Handler(
                self.__rpc_start_run,
                grpclib.const.Cardinality.UNARY_UNARY,
                StartRunRequest,
                StartRunResponse,
            ),
            "/actor.v1.ActorService/WaitForRun": grpclib.const.Handler(
                self.__rpc_wait_for_run,
                grpclib.const.Cardinality.UNARY_UNARY,
                WaitForRunRequest,
                WaitForRunResponse,
            ),
            "/actor.v1.ActorService/RunActor": grpclib.const.Handler(
                self.__rpc_run_actor,
                grpclib.const.Cardinality.UNARY_UNARY,
                RunActorRequest,
                RunActorResponse,
            ),
            "/actor.v1.ActorService/StopActor": grpclib.const.Handler(
                self.__rpc_stop_actor,
                grpclib.const.Cardinality.UNARY_UNARY,
                StopActorRequest,
                StopActorResponse,
            ),
            "/actor.v1.ActorService/GetActor": grpclib.const.Handler(
                self.__rpc_get_actor,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetActorRequest,
                GetActorResponse,
            ),
            "/actor.v1.ActorService/ActorExists": grpclib.const.Handler(
                self.__rpc_actor_exists,
                grpclib.const.Cardinality.UNARY_UNARY,
                ActorExistsRequest,
                ActorExistsResponse,
            ),
            "/actor.v1.ActorService/ListActors": grpclib.const.Handler(
                self.__rpc_list_actors,
                grpclib.const.Cardinality.UNARY_UNARY,
                ListActorsRequest,
                ListActorsResponse,
            ),
            "/actor.v1.ActorService/ActorStatus": grpclib.const.Handler(
                self.__rpc_actor_status,
                grpclib.const.Cardinality.UNARY_UNARY,
                ActorStatusRequest,
                ActorStatusResponse,
            ),
            "/actor.v1.ActorService/LatestRun": grpclib.const.Handler(
                self.__rpc_latest_run,
                grpclib.const.Cardinality.UNARY_UNARY,
                LatestRunRequest,
                LatestRunResponse,
            ),
            "/actor.v1.ActorService/ShowActor": grpclib.const.Handler(
                self.__rpc_show_actor,
                grpclib.const.Cardinality.UNARY_UNARY,
                ShowActorRequest,
                ShowActorResponse,
            ),
            "/actor.v1.ActorService/ListRuns": grpclib.const.Handler(
                self.__rpc_list_runs,
                grpclib.const.Cardinality.UNARY_UNARY,
                ListRunsRequest,
                ListRunsResponse,
            ),
            "/actor.v1.ActorService/GetRun": grpclib.const.Handler(
                self.__rpc_get_run,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetRunRequest,
                GetRunResponse,
            ),
            "/actor.v1.ActorService/GetLogs": grpclib.const.Handler(
                self.__rpc_get_logs,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetLogsRequest,
                GetLogsResponse,
            ),
            "/actor.v1.ActorService/ListRoles": grpclib.const.Handler(
                self.__rpc_list_roles,
                grpclib.const.Cardinality.UNARY_UNARY,
                ListRolesRequest,
                ListRolesResponse,
            ),
            "/actor.v1.ActorService/PublishNotification": grpclib.const.Handler(
                self.__rpc_publish_notification,
                grpclib.const.Cardinality.UNARY_UNARY,
                PublishNotificationRequest,
                PublishNotificationResponse,
            ),
            "/actor.v1.ActorService/SubscribeNotifications": grpclib.const.Handler(
                self.__rpc_subscribe_notifications,
                grpclib.const.Cardinality.UNARY_STREAM,
                SubscribeNotificationsRequest,
                Notification,
            ),
            "/actor.v1.ActorService/GetServerInfo": grpclib.const.Handler(
                self.__rpc_get_server_info,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetServerInfoRequest,
                GetServerInfoResponse,
            ),
            "/actor.v1.ActorService/ListServers": grpclib.const.Handler(
                self.__rpc_list_servers,
                grpclib.const.Cardinality.UNARY_UNARY,
                ListServersRequest,
                ListServersResponse,
            ),
            "/actor.v1.ActorService/InteractiveSession": grpclib.const.Handler(
                self.__rpc_interactive_session,
                grpclib.const.Cardinality.STREAM_STREAM,
                ClientFrame,
                ServerFrame,
            ),
        }
